spring:
  profiles:
    include:
      - dev
  application:
    name: BBS
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    username: ${MAIL_USERNAME:123456789@qq.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
    port: 465
    ssl:
      enabled: true
bbs:
  oss:
    secret-id: ${OSS_SECRET_ID:secret-id}
    secret-key: ${OSS_SECRET_KEY:secret-key}
    region: ${OSS_REGION:ap-guangzhou}
    avatar:
      bucket: ${OSS_AVATAR_BUCKET:avatar-bucket}
      allow-types:
        - "image/jpeg"
        - "image/png"
        - "image/gif"
        - "image/bmp"
        - "image/webp"
      max-size: 5MB
      prefix: "/avatars"
      expired-after: 30s
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expired-time: 2h
