name: Build Native Artifact

on:
  push:
    paths:
      - src
      - pom.xml
      - .github/workflows/test.yml
      - .github/workflows/native-build.yml
  pull_request:
    paths:
      - src
      - pom.xml
      - .github/workflows/test.yml
      - .github/workflows/native-build.yml
  workflow_dispatch:


jobs:
  tests:
    uses: ./.github/workflows/test.yml

  native-image:
    name: Build GraalVM Native Image
    needs: tests
    if: ${{ needs.run-tests.outputs.test-status != 'FAILED' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM JDK 23
        uses: graalvm/setup-graalvm@v1
        with: 
          java-version: '17.0.12'
          distribution: 'graalvm'
          cache: maven


      - name: Build native executable
        run: ./mvnw -Pnative -DskipTests native:compile

      - name: Package native artifacts
        run: |
          cd target
          find native -maxdepth 1 -name 'lib*.so' -exec cp {} . \;
          tar czf bbs-native-linux-x64.tar.gz bbs lib*.so

      - name: Upload native artifact
        uses: actions/upload-artifact@v4
        with:
          name: bbs-native-linux-x64
          path: target/bbs-native-linux-x64.tar.gz
